# Generated by Django 5.2 on 2025-04-15 20:03

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Телефон')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время регистрации')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('sensor_data_file', models.FileField(upload_to='', verbose_name='Файл с данными с датчиков')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TripAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_speed', models.FloatField(verbose_name='Средняя скорость (км/ч)')),
                ('distance', models.FloatField(verbose_name='Пройденное расстояние (км)')),
                ('hard_brakes', models.IntegerField(verbose_name='Частота резких торможений')),
                ('hard_accels', models.IntegerField(verbose_name='Частота резких ускорений')),
                ('avg_yaw_rate', models.FloatField(verbose_name='Средняя угловая скорость')),
                ('sharp_turns', models.IntegerField(verbose_name='Число резких маневров')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.trip', verbose_name='Поездка')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория стиля')),
                ('recommendations', models.TextField(verbose_name='Рекомендации')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.tripanalysis', verbose_name='Анализ поездки')),
            ],
        ),
        migrations.CreateModel(
            name='UserDrivingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips', models.IntegerField(verbose_name='Общее число поездок')),
                ('total_distance', models.FloatField(verbose_name='Пройденное расстояние (км)')),
                ('avg_speed', models.FloatField(verbose_name='Средняя скорость (км/ч)')),
                ('avg_brakes', models.FloatField(verbose_name='Среднее число резких торможений')),
                ('avg_accels', models.FloatField(verbose_name='Среднее число резких ускорений')),
                ('avg_yaw_rate', models.FloatField(verbose_name='Средняя угловая скорость')),
                ('overall_category', models.CharField(max_length=50, verbose_name='Общая категория стиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
