# Generated by Django 5.2 on 2025-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripanalysis',
            old_name='avg_yaw_rate',
            new_name='avg_gyro_mag',
        ),
        migrations.RenameField(
            model_name='userdrivingprofile',
            old_name='avg_yaw_rate',
            new_name='avg_gyro_mag',
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='trip_duration',
            field=models.FloatField(default=1, verbose_name='Длительность поездки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdrivingprofile',
            name='avg_sharp_turns',
            field=models.IntegerField(default=1, verbose_name='Среднее число резких маневров'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='sensor_data_file',
            field=models.FileField(upload_to='sensor_data', verbose_name='Файл с данными с датчиков'),
        ),
    ]
