# Generated by Django 5.2 on 2025-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_sensor_data_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripanalysis',
            old_name='avg_yaw_rate',
            new_name='avg_gyro_mag',
        ),
        migrations.AddField(
            model_name='tripanalysis',
            name='trip_duration',
            field=models.FloatField(default=1, verbose_name='Длительность поездки'),
            preserve_default=False,
        ),
    ]
