# Generated by Django 5.2 on 2025-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_rename_avg_yaw_rate_tripanalysis_avg_gyro_mag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdrivingprofile',
            name='avg_sharp_turns',
            field=models.FloatField(verbose_name='Среднее число резких маневров'),
        ),
    ]
