# Generated by Django 5.2 on 2025-05-11 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_userdrivingprofile_avg_sharp_turns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end_time',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_time',
            new_name='start_date_time',
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
