# Generated by Django 5.2 on 2025-05-21 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_rename_end_time_trip_end_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingstyle',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания оценки'),
        ),
        migrations.AlterField(
            model_name='drivingstyle',
            name='category',
            field=models.CharField(choices=[('smooth', 'плавный'), ('moderate', 'умеренный'), ('aggressive', 'агрессивный')], verbose_name='Категория стиля'),
        ),
    ]
